### ISSUE TITLE
Swift Support

### ISSUE THREAD

**Issue by moderateepheezy** [kuler90/RKTagsView#10]
Does it have a swift version, or can you guide me on how to use this in a Swift project.

**Comment by kuler90** [comment]
Hi! RKTagsView does not have Swift version but I adopt it for using in Swift code by marking optional and generic types. Here is a link to guide how to use Objective C pod with Swift - http://stackoverflow.com/a/31885253.

**Comment by ShadeApps** [comment]
Any chances to do get native Swift support in the near future?
Or better aim for a Swift fork done by enthusiasts?

**Comment by tblanchard** [comment]
The smart component builder will build components in Objective C so everybody can use them since embedding Swift into an Objective C project doesn't really work and worse - it encumbers the project with the entire Swift runtime (15M+) and makes build times crawl.

Smart developers are not trying to use Swift for production code yet and wont until the Swift compiler is on par with the Objective C one in speed and stability.  Its about 10x slower just now.  I don't have time for that.

**Comment by ShadeApps** [comment]
Thanks, @tblanchard 

I use this control in a multitude of Swift-first apps and was looking into forking it and rewriting it natively in Swift. Probably will do this soon in my free time.

**Comment by tblanchard** [comment]
There is no value to rewriting it.  Swift is a scripting language that rides atop the Objective C runtime most of the time.

You can just use it as is.
